package bachelor:backend@0.1.0;

interface sql {
  type error = u32;

  enum db-operation {
    select,
    insert,
    delete,
    unknown,
  }

  resource connection; 
  open-connection: func(url: string, create-if-missing: bool) -> result<connection, error>;
  drop-connection: func(conn: connection) -> result<_, error>;

  create-table: func(query: string, conn: borrow<connection>);

  execute-query: func(conn: borrow<connection>, query: string, values: option<string>) -> result<option<string>, error>;

  select: func(conn: borrow<connection>) -> result<string, error>;
  insert: func(conn: borrow<connection>, name: string);
  delete: func(conn: borrow<connection>, name: string);

  print-to-host: func(str: string);
}

interface sql-handler {
  use sql.{error};
  db-test: func() -> result<_, error>;
}

interface tcp {
  use sql.{db-operation};
  type error = u32;

  resource socket;
  resource tcp-stream;

  enum message-type {
    dht11,
    test,
    unknown,
  }

  record test-message-data {
    message-type: string,
    operation: db-operation,
    id: option<u32>,
    name: option<string>,
  }

  record dht11-data {
    message-type: string,
    operation: db-operation,
    id: option<u32>,
    temperature: option<s32>,
    humidity: option<u32>,
  }

  variant message-data {
    dht11(dht11-data),
    test-message(test-message-data),
    none
  }

  create-socket: func(addr: string) -> result<socket, error>;
  accept: func(sock: borrow<socket>) -> result<tcp-stream, error>;
  read: func(sock: borrow<socket>, inc-str: borrow<tcp-stream>) -> result<string, error>;
  close-stream: func(sock: borrow<socket>, inc-str: tcp-stream);

  parse-data: func(message: string) -> result<message-data, error>;
}

interface sockets-handler {
  use tcp.{error, socket, test-message-data};
  socket-handle: func() -> result<_, error>;
  init-db: func() -> result<_, error>;
  handle-test-message: func(data: test-message-data) -> result<_, error>;
}

world server {
  import tcp;
  include wasi:sockets/imports@0.2.0;
}

world database {
  import sql;
}

world backend {
  export sockets-handler;
}
