package local:plot;

interface plot-functions {
  resource dht11 {
    constructor(ids: list<s32>, temperatures: list<s32>, humidities: list<s32>);
  }

  build-dht11-data: func(ids: list<s32>, temperatures: list<s32>, humidities: list<s32>) -> dht11;

  plot-line-chart: func(x: s32, y: s32, element-id: string);

  hello: func(name: string) -> string;
}

world plot {
  export plot-functions;
}
