// Generated by `wit-bindgen` 0.24.0. DO NOT EDIT!
#ifndef __BINDINGS_EXAMPLE_H
#define __BINDINGS_EXAMPLE_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>

// Exported Functions from `example:component/adder@0.1.0`
int32_t exports_example_component_adder_add(int32_t x, int32_t y);

#ifdef __cplusplus
}
#endif
#endif
