// Generated by `wit-bindgen` 0.24.0. DO NOT EDIT!
#include "board.h"
#include <stdlib.h>

// Exported Functions from `esp:monitor/native-functions@0.1.0`

// Exported Functions from `esp:monitor/monitor@0.1.0`

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc"))) void *
cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void)old_size;
  if (new_size == 0)
    return (void *)align;
  void *ret = realloc(ptr, new_size);
  if (!ret)
    abort();
  return ret;
}

// Component Adapters

__attribute__((__aligned__(4))) static uint8_t RET_AREA[12];

__attribute__((__export_name__(
    "esp:monitor/native-functions@0.1.0#initilize-sensors"))) void
__wasm_export_exports_esp_monitor_native_functions_initilize_sensors(void) {
  exports_esp_monitor_native_functions_initilize_sensors();
}

__attribute__((__export_name__(
    "esp:monitor/native-functions@0.1.0#read-humidity"))) int32_t
__wasm_export_exports_esp_monitor_native_functions_read_humidity(void) {
  int32_t ret = exports_esp_monitor_native_functions_read_humidity();
  return ret;
}

__attribute__((__export_name__(
    "esp:monitor/native-functions@0.1.0#read-temperature"))) int32_t
__wasm_export_exports_esp_monitor_native_functions_read_temperature(void) {
  int32_t ret = exports_esp_monitor_native_functions_read_temperature();
  return ret;
}

__attribute__((
    __export_name__("esp:monitor/native-functions@0.1.0#read-status"))) int32_t
__wasm_export_exports_esp_monitor_native_functions_read_status(void) {
  int32_t ret = exports_esp_monitor_native_functions_read_status();
  return ret;
}

__attribute__((__export_name__(
    "esp:monitor/native-functions@0.1.0#get-wifi-status"))) int32_t
__wasm_export_exports_esp_monitor_native_functions_get_wifi_status(void) {
  int32_t ret = exports_esp_monitor_native_functions_get_wifi_status();
  return ret;
}

__attribute__((
    __export_name__("esp:monitor/native-functions@0.1.0#build-message"))) void
__wasm_export_exports_esp_monitor_native_functions_build_message(int32_t arg,
                                                                 int32_t arg0,
                                                                 int32_t arg1,
                                                                 int32_t arg2) {
  exports_esp_monitor_native_functions_build_message(
      (uint32_t)(arg), (uint32_t)(arg0), arg1, arg2);
}

__attribute__((
    __export_name__("esp:monitor/native-functions@0.1.0#fifo-init"))) void
__wasm_export_exports_esp_monitor_native_functions_fifo_init(void) {
  exports_esp_monitor_native_functions_fifo_init();
}

__attribute__((__export_name__("esp:monitor/native-functions@0.1.0#put")))
int32_t
__wasm_export_exports_esp_monitor_native_functions_put(int32_t arg) {
  int32_t ret = exports_esp_monitor_native_functions_put((uint32_t)(arg));
  return ret;
}

__attribute__((__export_name__("esp:monitor/monitor@0.1.0#run"))) int32_t
__wasm_export_exports_esp_monitor_monitor_run(void) {
  int32_t ret = exports_esp_monitor_monitor_run();
  return ret;
}

__attribute__((__export_name__("esp:monitor/monitor@0.1.0#read-dht11-sensor")))
uint8_t *
__wasm_export_exports_esp_monitor_monitor_read_dht11_sensor(void) {
  exports_esp_monitor_monitor_dht11_sensor_values_t ret;
  exports_esp_monitor_monitor_read_dht11_sensor(&ret);
  uint8_t *ptr = (uint8_t *)&RET_AREA;
  *((int32_t *)(ptr + 0)) = (ret).temperature;
  *((int32_t *)(ptr + 4)) = (ret).humidity;
  *((int32_t *)(ptr + 8)) = (ret).status;
  return ptr;
}

__attribute__((__export_name__("esp:monitor/monitor@0.1.0#valid-values")))
int32_t
__wasm_export_exports_esp_monitor_monitor_valid_values(int32_t arg,
                                                       int32_t arg0,
                                                       int32_t arg1) {
  exports_esp_monitor_monitor_dht11_sensor_values_t arg2 =
      (exports_esp_monitor_monitor_dht11_sensor_values_t){
          (int32_t)arg,
          (int32_t)arg0,
          (int32_t)arg1,
      };
  int32_t ret = exports_esp_monitor_monitor_valid_values(&arg2);
  return ret;
}

__attribute__((__export_name__("esp:monitor/monitor@0.1.0#valid-status")))
int32_t
__wasm_export_exports_esp_monitor_monitor_valid_status(int32_t arg,
                                                       int32_t arg0,
                                                       int32_t arg1) {
  exports_esp_monitor_monitor_dht11_sensor_values_t arg2 =
      (exports_esp_monitor_monitor_dht11_sensor_values_t){
          (int32_t)arg,
          (int32_t)arg0,
          (int32_t)arg1,
      };
  int32_t ret = exports_esp_monitor_monitor_valid_status(&arg2);
  return ret;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_board(void);
void __component_type_object_force_link_board_public_use_in_this_compilation_unit(
    void) {
  __component_type_object_force_link_board();
}
