// Generated by `wit-bindgen` 0.24.0. DO NOT EDIT!
#ifndef __BINDINGS_BOARD_H
#define __BINDINGS_BOARD_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>

typedef struct exports_esp_monitor_monitor_dht11_sensor_values_t {
  int32_t   temperature;
  int32_t   humidity;
  int32_t   status;
} exports_esp_monitor_monitor_dht11_sensor_values_t;

// Exported Functions from `esp:monitor/native-functions@0.1.0`
void exports_esp_monitor_native_functions_initilize_sensors(void);
int32_t exports_esp_monitor_native_functions_read_humidity(void);
int32_t exports_esp_monitor_native_functions_read_temperature(void);
int32_t exports_esp_monitor_native_functions_read_status(void);
int32_t exports_esp_monitor_native_functions_get_wifi_status(void);
void exports_esp_monitor_native_functions_build_message(uint32_t buf_ptr, uint32_t buf_size, int32_t temperature, int32_t humidity);
void exports_esp_monitor_native_functions_fifo_init(void);
int32_t exports_esp_monitor_native_functions_put(uint32_t msg_ptr);

// Exported Functions from `esp:monitor/monitor@0.1.0`
int32_t exports_esp_monitor_monitor_run(void);
void exports_esp_monitor_monitor_read_dht11_sensor(exports_esp_monitor_monitor_dht11_sensor_values_t *ret);
int32_t exports_esp_monitor_monitor_valid_values(exports_esp_monitor_monitor_dht11_sensor_values_t *values);
int32_t exports_esp_monitor_monitor_valid_status(exports_esp_monitor_monitor_dht11_sensor_values_t *values);

#ifdef __cplusplus
}
#endif
#endif
