package backend:server@0.1.0;

interface server-handle {
  use wasi:sockets/udp@0.2.0.{udp-socket};
  use wasi:sockets/network@0.2.0.{error-code};
  handle: func() -> result<_, error-code>;
  socket-receive: func(sock: borrow<udp-socket>) -> result<list<u8>, error-code>;
}

world server {
  include wasi:sockets/imports@0.2.0;
  export server-handle;
}
